// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('BApp', ["BApp.Charts.Traffic"]);

  app.controller('BMainCtrl', function() {});

  app.factory('d3', function() {
    return d3;
  });

}).call(this);

//# sourceMappingURL=app.map
