// Generated by CoffeeScript 1.7.1
(function() {
  var app, cache, config, dataApi, express, ga, server;

  express = require('express');

  config = require("./server/config");

  ga = require("./server/ga");

  cache = require('./server/cache');


  /*
   * Server & API
   */

  app = express();

  dataApi = express.Router();

  dataApi.param('type', function(req, res, next, id) {
    var err;
    if (ga.validQueryTypes.indexOf(id) === -1) {
      err = new Error("Wrong request data type.");
      console.log("ERROR: " + err.message);
      res.json(500, {
        error: err.message
      });
    } else {
      req.type = id;
      next();
    }
  });

  dataApi.route('/data/:type').all(function(req, res, next) {
    console.log(req.method, req.type, req.path);
    next();
  }).get(function(req, res) {
    cache.fetch(req.type).then(function(data) {
      res.json(data);
    });
  });

  app.use(dataApi);

  app.use(express["static"]('public'));

  server = app.listen(3000, function() {
    console.log("INFO: listening on port " + (server.address().port) + ".");
  });

}).call(this);

//# sourceMappingURL=index.map
