// Generated by CoffeeScript 1.7.1
(function() {
  var module;

  module = angular.module('BApp.Charts.Traffic', []);

  module.directive("traffic", function(d3) {
    return {
      templateUrl: 'bapp-charts-traffic/partial.html',
      restrict: 'E',
      link: function(scope, ele) {
        console.log(d3);
      }
    };
  });

}).call(this);

//# sourceMappingURL=module.map
